let cur=new Date(new Date().getFullYear(),new Date().getMonth(),1), monthData=null;
const $=s=>document.querySelector(s), esc=x=>String(x??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const dk=d=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;
const key=()=>`${cur.getFullYear()}-${String(cur.getMonth()+1).padStart(2,'0')}`;
function init(){if(!window.FIREBASE_READY){location.href='index.html';return;}firebase.initializeApp(window.FIREBASE_CONFIG);const auth=firebase.auth();auth.onAuthStateChanged(async u=>{if(!u)return location.href='index.html';const token=await u.getIdTokenResult();const role=token.claims.role;if(role!=='admin'&&role!=='mantenimiento')return auth.signOut();$('#roleBadge').textContent=role==='mantenimiento'?'MTTO':'ADMIN';if(role==='admin')$('#adminLink').classList.remove('hidden');$('#logout').onclick=()=>auth.signOut().then(()=>location.href='index.html');load();});}
async function load(){ $('#loading').classList.remove('hidden'); try{const s=await firebase.database().ref('calendar/'+key()).once('value');monthData=s.val();render();}catch(e){alert('No se pudo cargar el calendario: '+e.message)}finally{$('#loading').classList.add('hidden');}}
function render(){if(!monthData){$('#planTable').innerHTML='<tbody><tr><td class="empty-cell">Todavía no hay un calendario publicado para este mes.</td></tr></tbody>';$('#month').textContent=new Intl.DateTimeFormat('es-AR',{month:'long',year:'numeric'}).format(cur);return;}$('#month').textContent=new Intl.DateTimeFormat('es-AR',{month:'long',year:'numeric'}).format(cur);const rows=monthData.people||[],ds=monthData.days||[],gf=$('#fg').value,pf=$('#fp').value;let ps=rows.filter(p=>(!pf||p.id===pf)&&(!gf||p.groupId===gf));let h='<thead><tr><th class="sticky n">Persona</th><th class="sticky g">Grupo</th>';ds.forEach(d=>h+=`<th class="${d.weekend?'weekend':''}">${d.day}<small>${esc(d.weekday)}</small></th>`);h+='</tr></thead><tbody>';let last='';ps.forEach(p=>{if(p.groupId!==last){h+=`<tr class="group"><td colspan="${ds.length+2}">${esc(p.groupName||'Fuera de rotación / sin grupo')}</td></tr>`;last=p.groupId;}h+=`<tr><td class="sticky n person">${esc(p.name)} ${p.badge?`<span class="mini">${esc(p.badge)}</span>`:''}</td><td class="sticky g">${esc(p.groupName||'—')}</td>`;ds.forEach(d=>{const a=p.days[d.date]||{label:'—',class:'out'};h+=`<td class="cell ${a.class} ${d.weekend?'weekend':''}" title="${esc(a.detail||a.label)}"><b>${esc(a.label)}</b></td>`});h+='</tr>';});h+='</tbody>';$('#planTable').innerHTML=h;fillFilters(rows);}
function fillFilters(rows){const g=$('#fg'),p=$('#fp'),gv=g.value,pv=p.value;const groups=[...new Map(rows.filter(x=>x.groupId).map(x=>[x.groupId,x.groupName])).entries()];g.innerHTML='<option value="">Todos los grupos</option>'+groups.map(([id,n])=>`<option value="${esc(id)}">${esc(n)}</option>`).join('');p.innerHTML='<option value="">Todas las personas</option>'+rows.map(x=>`<option value="${esc(x.id)}">${esc(x.name)}</option>`).join('');g.value=gv;p.value=pv;}
$('#prev').onclick=()=>{cur.setMonth(cur.getMonth()-1);load()};$('#next').onclick=()=>{cur.setMonth(cur.getMonth()+1);load()};$('#today').onclick=()=>{const n=new Date();cur=new Date(n.getFullYear(),n.getMonth(),1);load()};$('#fg').onchange=render;$('#fp').onchange=render;document.addEventListener('DOMContentLoaded',init);
